# CI 4º Nível - Pipeline Integrada ao Build do Código

name: "04- Execução Integrada"

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

# Permissões necessárias para publicar no GitHub Pages e criar os reports
permissions:
  id-token: write
  contents: write
  checks: write
  pull-requests: write

jobs:
  inspecao:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalando o Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: "yarn"

      - name: Instalando o yarn
        run: npm install -g yarn

      - name: Instalando as dependências
        run: yarn install

      - name: Inspeção de Código
        run: yarn lint

  testes:
    runs-on: ubuntu-latest
    needs: [inspecao]
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalando o Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: "yarn"

      - name: Instalando o yarn
        run: npm install -g yarn

      - name: Instalando as dependências
        run: yarn install

      # Instalar os browsers ANTES de rodar os testes
      - name: Instalando os browsers e dependências do Playwright
        run: yarn playwright install --with-deps

      # Executa os testes gerando JUnit XML, Mochawesome HTML, CTRF JSON e Allure Results juntos
      - name: Executando os testes
        run: yarn run test

      - name: Exibir Resultados no GitHub
        uses: dorny/test-reporter@v3
        if: ${{ always() }}
        with:
          name: Mocha Tests
          path: results.xml
          reporter: jest-junit

      # Salva a pasta HTML gerada pelo Mochawesome
      - name: Salvar Relatorio HTML para Download
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: relatorio-testes-html
          path: mochawesome-report/

      # Geração do Dashboard Allure
      - name: Instalar utilitário do Allure
        if: ${{ always() }}
        run: npm install -g allure-commandline --save-dev

      - name: Gerar Relatório HTML do Allure
        if: ${{ always() }}
        run: allure generate allure-results --clean -o allure-report

      # Publica o relatório no GitHub Pages automaticamente
      - name: Publicar Relatório no GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ always() }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report

      # Plugin git-hub-test-reporter (CTRF)
      - name: Publish Test Report
        uses: ctrf-io/github-test-reporter@v1
        with:
          report-path: "**/ctrf-report.json"
          summary-delta-report: true
          insights-report: true
          flaky-rate-report: true
          fail-rate-report: true
          slowest-report: true
          upload-artifact: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ always() }}

  deploy:
    runs-on: ubuntu-latest
    needs: [testes]
    steps:
      - name: Simulação de Deploy
        run: echo 'Deploy sendo realizado!!'
